### ISSUE TITLE
Unable to create new quotes or duplicate quotes 

### ISSUE THREAD

**Issue by shannoding** [ABTech/tracker#484]
The "Create new invoice" button in the invoices section has disappeared for seemingly all events (past, future, billable, etc.). Trying to duplicate an existing invoice from the event page results in an "Error duplicating invoice!".

See Pre-College 2022 for an example.

Editing and saving existing invoices is fine.

**Comment by DaAwesomeP** [comment]
Pushing a fix shortly to show make Tracker show the error in more detail.

This time specifically the issue is "Event is not in the current billing year." I believe we have run into this issue before. Tracker marks the change of the billing year as 7/1. It calculates this by start date, so I will see if I can make it consider the current year a bit differently.

**Comment by DaAwesomeP** [comment]
OK, to be more specific, it is calculating which school year an event occurs in by the start date of the first event date of the event. The crossover point for the school year is 7/1 (according to Tracker). So, I will make it treat an event as in the current year if either the start of the first event date is in this year or if the end of the last event date is in this year.
