### ISSUE TITLE
Add shoulder runcrew positions

### ISSUE THREAD

**Issue by arstrasser** [ABTech/tracker#510]
In addition to aPositions, add sPositions:
- sTiC
- sFoH
- sMon
- sLD
- sME
- sMR
- sSM
- sMedia
- sHole
- sAirhorn

Supervise position should just be renamed to sTiC.

This change has been discussed and approved by all officers.

**Comment by DaAwesomeP** [comment]
@arstrasser Would you like me to work on this or assign it to someone else?

**Comment by arstrasser** [comment]
If you know of anyone who is interested and capable would be great to pass it off, but if you think it will be a lot of effort or will take more than a week, then you should just take care of it

**Comment by DaAwesomeP** [comment]
@izhanchang May you please draft a description like the one below but for `s*` positions? This is for the reference page.
> a*: Sometimes run position titles have an 'a' in front of them, such as aTiC, aFoH, or aLD. This indicates an assistant position, which aids the respective run crew member in their duties. The way the assistant helps is entirely up to the main run crew member. However, many times run crew members will open up 'a' positions in order to train new members alongside helping with duties. If you see an 'a' position open up for a role that you are interested in, feel free to apply!

**Comment by DaAwesomeP** [comment]
OK, here is what I have implemented:

1. If an event does not have any runcrew and someone applies to any position, the email goes to inbox (no change).
2. If an event has a sTiC and someone applies to TiC, then the email goes to the sTiC.
3. If an event has a sTiC and a TiC and someone applies to another TiC position, then the email goes to the sTiC.
4. If someone applies to aTiC, then the email goes to both the sTic and TiC.
5. If someone applies to FoH, the email will go to sFoH if it exists, otherwise TiC and sTiC.

Essentially, any role applications bound to be delivered to the non general position will also be delivered to the respective `s*` position.

**Comment by izhanchang** [comment]
s*: Shoulder positions, such as sTiC, sFoH, or sLD, are assistant positions
for experienced members. A main run crew member may be ready to take a show
on their own, but want someone more experienced around in case any issues
arise. In this case, shoulders act as experienced assistants who are ready
to help troubleshoot and otherwise assist as the main run crew needs. If
you see an s* position open and are available to lend a helping shoulder,
please apply!

V2:
s*: Shoulder positions, such as sTiC, sFoH, or sLD, are assistant positions
for experienced members. A main run crew member may be ready to take a show
on their own, but want someone more experienced around in case any issues
arise. In this case, shoulders act as experienced assistants who are ready
to help troubleshoot and otherwise assist as the main run crew needs. If
you see an s* position open and are available to lend a helping head,
shoulder, knee or toe (but mostly shoulder), please apply!

**Comment by DaAwesomeP** [comment]
@izhanchang Thanks! I'll go with V2.
